/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library '4fc6386402c041c6558f07e421cc940f_dd6bb9f4ae91dae9c1c1ee95a847d8f1_8'
*/
/* 添加define定义 */

#define LOBYTE(x)   (*((uint8_t *)&(x)))
#define HIBYTE(x)   (*(((uint8_t *)&(x)) + 1))
#define LOWORD(x)   (*((uint16_t *)&(x)))
#define HIWORD(x)   (*(((uint16_t *)&(x)) + 1))
#define LODWORD(x)  (*((uint32_t *)&(x)))
#define HIDWORD(x)  (*(((uint32_t *)&(x)) + 1))
#define BYTE1(x) (*(((uint8_t *)&(x)) + 1))
#define BYTE2(x) (*(((uint8_t *)&(x)) + 2))
#define BYTE6(x) (*(((uint8_t *)&(x)) + 6))
#define bool int 
#define _QWORD uint64_t
#define _BOOL2 int

/* 添加声明 */
extern void _register_frame_info(void *, void *);
extern void *Jv_RegisterClasses(void *, void *);
extern void _deregister_frame_info(void *);

/* 添加变量定义 */
unsigned int unk_4A2DDC; 



#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

/* 1 */
struct Elf32_Sym
{
  unsigned __int32 st_name;
  unsigned __int32 st_value;
  unsigned __int32 st_size;
  unsigned __int8 st_info;
  unsigned __int8 st_other;
  unsigned __int16 st_shndx;
};

/* 2 */
union Elf32_Dyn_A263394DDF3EC2D4B1B8448EDD30E249
{
  unsigned __int32 d_val;
  unsigned __int32 d_ptr;
};

/* 3 */
struct Elf32_Dyn
{
  __int32 d_tag;
  union Elf32_Dyn_A263394DDF3EC2D4B1B8448EDD30E249 d_un;
};

typedef int BOOL;

typedef uint32_t _DWORD;

/* 重新定义一个free2()*/
int free2(void *ptr) {
    free(ptr);
    return 0; 
}